title: OpenSustain
description: Open source sustainability and maintainer-load analysis tool
github:
  repository_url: https://github.com/Demiserular/OPENSUSTAIN
  owner_name: Demiserular
  owner_url: https://github.com/Demiserular
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
